model:
  name_model_or_path: "./testing_dir/checkpoint-3120"
  name_image_processor_or_path: "nvidia/mit-b0"

dataset:
  path_to_data: "D:\\projects_andrey\\datasets\\segmentations\\landsat8"
  path_to_info_classes: "D:\\projects_andrey\\datasets\\segmentations\\landsat8\\classes.json"
